### ISSUE TITLE
Bug: mvn clean install doesn't work

### ISSUE THREAD

**Issue by CaptainRexPL** [collarmc/collar#23]
When I try to build collar using command "mvn clean install" I get an error:
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.collarmc.sdht.DistributedHashTableTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.321 s - in com.collarmc.sdht.DistributedHashTableTest
[INFO] Running com.collarmc.security.CollarIdentityTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.153 s - in com.collarmc.security.CollarIdentityTest
[INFO] Running com.collarmc.security.messages.GroupMessageTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in com.collarmc.security.messages.GroupMessageTest
[INFO] Running com.collarmc.security.messages.SignedMessageTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.collarmc.security.messages.SignedMessageTest
[INFO] Running com.collarmc.security.messages.SodiumCipherTest
[ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.003 s <<< FAILURE! - in com.collarmc.security.messages.SodiumCipherTest
[ERROR] eveCantReadBobsMessageToAlice(com.collarmc.security.messages.SodiumCipherTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: could not delete file collar\libsodium.dll
        at com.collarmc.security.messages.SodiumCipherTest.setup(SodiumCipherTest.java:29)

[ERROR] bobSendsMessageToAlice(com.collarmc.security.messages.SodiumCipherTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: could not delete file collar\libsodium.dll
        at com.collarmc.security.messages.SodiumCipherTest.setup(SodiumCipherTest.java:29)

[ERROR] encryptDecryptAndMutate(com.collarmc.security.messages.SodiumCipherTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: could not delete file collar\libsodium.dll
        at com.collarmc.security.messages.SodiumCipherTest.setup(SodiumCipherTest.java:29)

[ERROR] differentLengthMessages(com.collarmc.security.messages.SodiumCipherTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: could not delete file collar\libsodium.dll
        at com.collarmc.security.messages.SodiumCipherTest.setup(SodiumCipherTest.java:29)

[ERROR] bobEncryptsDataForHimself(com.collarmc.security.messages.SodiumCipherTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: could not delete file collar\libsodium.dll
        at com.collarmc.security.messages.SodiumCipherTest.setup(SodiumCipherTest.java:29)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   SodiumCipherTest.setup:29 » IllegalState could not delete file collar\libsodiu...
[ERROR]   SodiumCipherTest.setup:29 » IllegalState could not delete file collar\libsodiu...
[ERROR]   SodiumCipherTest.setup:29 » IllegalState could not delete file collar\libsodiu...
[ERROR]   SodiumCipherTest.setup:29 » IllegalState could not delete file collar\libsodiu...
[ERROR]   SodiumCipherTest.setup:29 » IllegalState could not delete file collar\libsodiu...
[INFO]
[ERROR] Tests run: 11, Failures: 0, Errors: 5, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] parent 0.1.0-SNAPSHOT .............................. SUCCESS [  9.811 s]
[INFO] api 0.1.0-SNAPSHOT ................................. SUCCESS [ 12.812 s]
[INFO] shared 0.1.0-SNAPSHOT .............................. FAILURE [  7.260 s]
[INFO] server 0.1.0-SNAPSHOT .............................. SKIPPED
[INFO] client 0.1.0-SNAPSHOT .............................. SKIPPED
[INFO] tests 0.1.0-SNAPSHOT ............................... SKIPPED
[INFO] tools 0.1.0-SNAPSHOT ............................... SKIPPED
[INFO] rest 0.1.0-SNAPSHOT ................................ SKIPPED
[INFO] molib 1.0 .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30.089 s
[INFO] Finished at: 2022-08-14T10:18:52+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project shared: There are test failures.
[ERROR]
[ERROR] Please refer to E:\collar-master\shared\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :shared

openJDK version: 16.0.2
Maven version: 3.8.6
branch: master
windows 10

**Comment by CaptainRexPL** [comment]
I tried to build this on a VM with Ubuntu (the JDK and Maven's versions are the same) and I get another error:
[INFO] ------------------------------------------------------- [INFO]  T E S T S [INFO] ------------------------------------------------------- [INFO] Running com.collarmc.server.services.location.NearbyGroupsTest [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.166 s - in com.collarmc.server.services.location.NearbyGroupsTest [INFO] Running com.collarmc.server.services.profile.storage.ProfileStorageTest [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.457 s - in com.collarmc.server.services.profile.storage.ProfileStorageTest [INFO] Running com.collarmc.server.services.profile.ProfileServiceTest [INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.447 s - in com.collarmc.server.services.profile.ProfileServiceTest [INFO] Running com.collarmc.server.services.groups.GroupStoreTest 20:53:14.046 [main] ERROR com.collarmc.server.configuration.Configuration - Starting in insecure development mode. Do not use in production. 20:53:14.623 [main] INFO  com.collarmc.server.configuration.Configuration - Using Email type LocalEmail [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.329 s <<< FAILURE! - in com.collarmc.server.services.groups.GroupStoreTest [ERROR] crud(com.collarmc.server.services.groups.GroupStoreTest)  Time elapsed: 1.329 s  <<< ERROR! java.lang.NullPointerException: Cannot read field "id" because "member.profile" is null         at com.collarmc.server.services.groups.GroupStoreTest.crud(GroupStoreTest.java:38)  [INFO] Running com.collarmc.server.http.ApiTokenTest [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.533 s - in com.collarmc.server.http.ApiTokenTest [INFO] Running com.collarmc.server.security.ServerIdentityStoreImplTest 20:53:16.037 [main] INFO  com.collarmc.server.security.ServerIdentityStoreImpl - Created new server identity 63b80222-835e-43be-8ee0-03c90a9abac0 20:53:16.040 [main] INFO  com.collarmc.server.security.ServerIdentityStoreImpl - Found server identity 63b80222-835e-43be-8ee0-03c90a9abac0 20:53:16.125 [main] INFO  com.collarmc.server.security.ServerIdentityStoreImpl - Created new server identity ab633120-8fa0-4d41-bf3e-c2ee370198ed 20:53:16.128 [main] INFO  com.collarmc.server.security.ServerIdentityStoreImpl - Found server identity ab633120-8fa0-4d41-bf3e-c2ee370198ed 20:53:16.191 [main] INFO  com.collarmc.server.security.ServerIdentityStoreImpl - Created new server identity 52120b80-c9df-467f-8c9a-5af4535e72f6 20:53:16.193 [main] INFO  com.collarmc.server.security.ServerIdentityStoreImpl - Found server identity 52120b80-c9df-467f-8c9a-5af4535e72f6 [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.292 s - in com.collarmc.server.security.ServerIdentityStoreImplTest [INFO]  [INFO] Results: [INFO]  [ERROR] Errors:  [ERROR]   GroupStoreTest.crud:38 » NullPointer Cannot read field "id" because "member.pr... [INFO]  [ERROR] Tests run: 11, Failures: 0, Errors: 1, Skipped: 0 [INFO]  [INFO] ------------------------------------------------------------------------ [INFO] Reactor Summary: [INFO]  [INFO] parent 0.1.0-SNAPSHOT .............................. SUCCESS [  3.921 s] [INFO] api 0.1.0-SNAPSHOT ................................. SUCCESS [  9.946 s] [INFO] molib 1.1.0-SNAPSHOT ............................... SUCCESS [  1.605 s] [INFO] shared 0.1.0-SNAPSHOT .............................. SUCCESS [ 24.249 s] [INFO] server 0.1.0-SNAPSHOT .............................. FAILURE [  9.010 s] [INFO] client 0.1.0-SNAPSHOT .............................. SKIPPED [INFO] tests 0.1.0-SNAPSHOT ............................... SKIPPED [INFO] tools 0.1.0-SNAPSHOT ............................... SKIPPED [INFO] rest 0.1.0-SNAPSHOT ................................ SKIPPED [INFO] ------------------------------------------------------------------------ [INFO] BUILD FAILURE [INFO] ------------------------------------------------------------------------ [INFO] Total time:  48.952 s [INFO] Finished at: 2022-08-15T20:53:16+02:00 [INFO] ------------------------------------------------------------------------ [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project server: There are test failures. [ERROR]


That's the report of this error: 
-------------------------------------------------------------------------------
Test set: com.collarmc.server.services.groups.GroupStoreTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.329 s <<< FAILURE! - in com.collarmc.server.services.groups.GroupStoreTest
crud(com.collarmc.server.services.groups.GroupStoreTest)  Time elapsed: 1.329 s  <<< ERROR!
java.lang.NullPointerException: Cannot read field "id" because "member.profile" is null
	at com.collarmc.server.services.groups.GroupStoreTest.crud(GroupStoreTest.java:38)

**Comment by CaptainRexPL** [comment]
Fixed in PR #29
